#!/bin/bash

DEVICES=`adb devices | tail  -n +2 | cut -f1`

for DEVICE in $DEVICES
do
  RUN="adb -s $DEVICE $@ &"
  echo $RUN
  ${RUN}
done

# adb devices | while read line
# do
#     if [ ! "$line" = "" ] && [ `echo $line | awk '{print $2}'` = "device" ]
#     then
#         device=`echo $line | awk '{print $1}'`
#         echo "$device $@ ..."
#         adb -s $device $@
#     fi
# done