name: 'Build & Test'
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         api-level: [22, 28, 30]
    env:
      JOB_ID: {{ github.job }}
    steps:
        - name: Print Env
          run: echo "Job - $GITHUB_JOB Run Id - $GITHUB_RUN_ID Run No - $GITHUB_RUN_NUMBER Job Id - $JOB_ID"
#       - name: Checkout the code
#         uses: actions/checkout@v2
#       - name: Enable Gradle Cache
#         uses: actions/cache@v1
#         with:
#           path: ~/.gradle/caches
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
#           restore-keys: ${{ runner.os }}-gradle-
#       - name: Seutp Fastlane
#         run: bundle update
#       - name: Run Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: ${{ matrix.api-level }}
#           arch: x86
#           profile: Nexus 6
#           target: google_apis
#           emulator-options: -no-window
#           script: bundle exec fastlane test_without_setup
