name: 'Build & Test'
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         api-level: [22, 28, 30]
    steps:
        - name: Print Env
          env:
            GITHUB: ${{ toJSON(github) }}
            ENV: ${{ toJSON(env) }}
            JOB: ${{ toJSON(job) }}
            STEPS: ${{ toJSON(steps) }}
            RUNNER: ${{ toJSON(runner) }}
          run: echo "GITHUB - $GITHUB ENV - $ENV , JOB - $JOB , STEPS - $STEPS , RUNNER - $RUNNER"
#       - name: Checkout the code
#         uses: actions/checkout@v2
#       - name: Enable Gradle Cache
#         uses: actions/cache@v1
#         with:
#           path: ~/.gradle/caches
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
#           restore-keys: ${{ runner.os }}-gradle-
#       - name: Seutp Fastlane
#         run: bundle update
#       - name: Run Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: ${{ matrix.api-level }}
#           arch: x86
#           profile: Nexus 6
#           target: google_apis
#           emulator-options: -no-window
#           script: bundle exec fastlane test_without_setup
